urlshortener/shortenersite/urls.py
from django.conf.urls import url
from shortenersite.views import index, redirect_original, shorten_url, urls_list
urlpatterns = [
    url(r'^$', index, name='home'),
    # for our home/index page

    url(r'^(?P<short_id>\w{6})$', redirect_original, name='redirectoriginal'),
    # when short URL is requested it redirects to original URL

    url(r'^makeshort/$', shorten_url, name='shortenurl'),
    # this will create a URL's short id and return the short URL
    url(r'^allurls/$', urls_list, name='urls_list'),
    ]

urlshortener/urlshortener/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    # if the URL pattern match /admin/ then open up admin panel

    url(r'', include('shortenersite.urls',
 namespace='shortenersite')),
    # if anything rather then /admin/ then it will look for shortenersite/urls
    ]

urlshortener/shortenersite/models.py
from django.db import models

# Create your models here.
class Urls(models.Model):
    short_id = models.SlugField(max_length=6,primary_key=True)
    httpurl = models.URLField(max_length=200)
    pub_date = models.DateTimeField(auto_now=True)
    count = models.IntegerField(default=0)
    text = models.TextField(default='')

def __str__(self):
    return self.httpurl

urlshortener/shortenersite/views.py
from django.shortcuts import render_to_response, get_object_or_404
import random, string, json
from shortenersite.models import Urls
from urlshortener.settings import SITE_URL
from django.http import HttpResponseRedirect, HttpResponse
from django.conf import settings
from django.template.context_processors import csrf
from django.shortcuts import render
from django.utils import timezone
from shortenersite.lib.customparser import get_text_from_page

def index(request):
    c = {}
    c.update(csrf(request))
    return render_to_response('shortenersite/index.html', c)

def redirect_original(request, short_id):
    url = get_object_or_404(Urls, pk=short_id) # get object, if not        found return 404 error
    url.count += 1
    url.save()
    return HttpResponseRedirect(url.httpurl)

def shorten_url(request):
    url = request.POST.get("url", '')
    user_short_url = request.POST.get("user_short_url", '')
    if not (url == ''):
        if not (user_short_url == ''):
            short_id = user_short_url
        else:
            short_id = get_short_code()
        text = get_text_from_page(url)
        b = Urls(httpurl=url, short_id=short_id, text=text)
        b.save()

        response_data = {}
        response_data['url'] = settings.SITE_URL + "/" + short_id
        return HttpResponse(json.dumps(response_data),  content_type="application/json")
    return HttpResponse(json.dumps({"error": "error occurs"}), content_type="application/json")

def get_short_code():
    length = 6
    char = string.ascii_uppercase + string.digits + string.ascii_lowercase
    # if the randomly generated short_id is used then generate next
    while True:
        short_id = ''.join(random.choice(char) for x in range(length))
        try:
            temp = Urls.objects.get(pk=short_id)
        except:
            return short_id

def urls_list(request):
    urls = Urls.objects.order_by('pub_date')
    return render(request, 'shortenersite/allurls.html', {'urls': urls, 'site_url': SITE_URL})

urlshortener/shortenersite/templates/shortenersite/allurls.html
{% extends "shortenersite/base.html" %}

{% block title %}URL Shortner - Make your URL shorter!{% endblock %}

{% block content %}

<div class="panel panel-default">
 <div class="panel-body">
    <div id="wrap">
      <h4><strong>Count of short URL's:</strong>&emsp;{{ urls|length }}</h4>
    </div>
  </div>
</div>

  {% for url in urls %}
  <div class="panel panel-default">
   <div class="panel-body">
      <div id="wrap">
          <h4><strong>Published:</strong>&emsp;{{ url.pub_date }}</h4>
          <h4><strong>Short ref:</strong><a href="{{ url.httpurl }}">&emsp;{{ site_url|add:url.short_id }}</a></h4>
          <h4><strong>Long ref:</strong><a href="{{ url.httpurl }}">&emsp;{{ url.httpurl }}</a></h4>
          <h4><strong>Text:</strong>&emsp;{{ url.text }}</h4>
          <h4><strong>Redirect count:</strong>&emsp;{{ url.count }}</h4>
      </div>
    </div>
  </div>

  {% endfor %}

{% endblock %}

urlshortener/shortenersite/templates/shortenersite/base.html
<!DOCTYPE html>
<html>
<head>
 <title>{% block title %}Welcome to mysite{% endblock %}</title>
 {% load staticfiles %}
 <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap.min.css">
 <link rel="stylesheet" type="text/css" href="{% static 'shortenersite/css/custom.css' %}" />
 <script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
 <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<script type="text/javascript">
 $(function() {
 $('#submitButton').click(function() {
 $.ajax({
 type: "POST",
 url: "/makeshort/",
 data: {
 'url' : $('#url').val(),
 'user_short_url' : $('#user_short_url').val(),
 'csrfmiddlewaretoken' : $("input[name=csrfmiddlewaretoken]").val()
 },
 success: returnSuccess,
 dataType: 'json'
 });
 });
});

function returnSuccess(data, textStatus, jqXHR) {
 if(data.url) {
 $('#url-result').text(data.url);
 $('#url').val("");
 $('#user_short_url').val("");
 } else {
 $('#url-result').text("Do not submit blank.");
 }

}
</script>
<body>
<div id="wrap">
<header>
 <div id="mainlogo"><a href="{% url 'shortenersite:home' %}">URL Shortener</a></div>
 <a href="{% url 'shortenersite:urls_list' %}" class="btn btn-default">All urls</a>
 <a href="{% url 'admin:index' %}" class="btn btn-default" target="_blank">Admin panel</a>
</header>

<div id="content">
{% block content %}

{% endblock %}
</div>
</div>
</body>
</html>

urlshortener/shortenersite/templates/shortenersite/index.html
{% extends "shortenersite/base.html" %}

{% block title %}URL Shortner - Make your URL shorter!{% endblock %}

{% block content %}

<div class="panel panel-default">
 <div class="panel-body">
 <div class="col-sm-9">
 <input type="text" name="url" id="url" class="form-control input-sm" placeholder="http://www.facebook.com" />
  </br>
 <input type="text" name="user_short_url" id="user_short_url" class="form-control input-sm" placeholder="input your short url" maxlength="6"/>
 </div>
 <div class="col-sm-3">
 {% csrf_token %}
 <button id="submitButton" class="btn btn-primary">Submit</button></p>
 </div>
 </div>
 <div class="panel-footer"><span id="url-result">Enter the URL above and click submit!</span></div>
</div>


{% endblock %}